[package]
name = "auto-ffmpeg-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
lettre = "0.11.17"
serde = { version = "1.0.219", features = ["derive"] }
signal-hook = "0.3.18"
toml = "0.9.0"
